spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flag_lecture?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112233
  jwt:
    secret-Key: FlagStudy
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
        use-new-id-generator-mappings: false